language: php

sudo: false

addons:
  firefox: latest
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
 global:
  - DB=pgsql
  - IGNORE_PATHS=vendor/
  - MOZ_HEADLESS=1

matrix:
  include:
  - env: MOODLE_BRANCH=MOODLE_35_STABLE
    php: 7.0
  - env: MOODLE_BRANCH=MOODLE_35_STABLE
    php: 7.2
  - env: MOODLE_BRANCH=MOODLE_36_STABLE
    php: 7.0
  - env: MOODLE_BRANCH=MOODLE_36_STABLE
    php: 7.3
  - env: MOODLE_BRANCH=MOODLE_37_STABLE
    php: 7.1
  - env: MOODLE_BRANCH=MOODLE_37_STABLE
    php: 7.3

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
